permalink: /blog/:year/:month/:day/:title.html
pygments: true

exclude: [config.ru, Gemfile, Gemfile.lock, jbhannah.net.sublime-project, jbhannah.net.sublime-workspace, LICENSE.txt, newrelic.yml, Procfile, Rakefile, README.md, vendor]
